@host = http://localhost
@port = 7088
@FrontLineCleaners.API_HostAddress = https://localhost:7088
@token = CfDJ8P0E7vemrNBKtEfmnBM7QgqoFrQLWqmHqCW9sG6Tx8bpVZNi4btxfdXrsZ34HcbNBHmSfJpsObYg0VvWTYWKe_wlsKvetvWioG1_S-GD67SW3M-4AEw40EN-32Xk0uer8D5cvVPtiuvh-FYeLCaZeSmUXv2ZyYP00D7Bzn5SvZ1vgHytjJjulByMxQJQ3s8LynZSI6nPK_66nkbVlfRd4wvQSvqZ8oXaqWA2Mh5jGRJ-4tcjvxdqrkkNOyBkN0VEEV8cVjjC4T6ekuDE4jkBrEBPzYvzD-BGj6xueRe39TFkIBplIgYh0_e8f7jH-DZjYWqVVhDSwd4rj9mFi3wieTQ6pYD_ny5SjSmahsALZl5F8P7eKP6LLcV9-hpctHiiLDctFGjQW4zbzyjMoml-F7eLon02p9n0KqACh1raFyxpzq75jFUJnUJyUdUhqr3ngbrOHCZf9aYjEswplT-q3ChQDCTAwhch4q37XJrOajG6XXzLsovHAWfGvqqDXMWD7MB8-yQbkNDz-UxR-KaxokMJIWtbBGaBu-2puEcYwRxy0dypxrKxSbi-V1xHzDNO1En7-klgATw6n9I0Jtmj7xDCBqOB44YKBTyANCgObx39GQCHGQzPyoIRFxZ9dQ0mLpZUz-AipnKIQSR5xRNZNypM4FqNwwlhHTjwx3cVJA-pRS6PjJXJuUiZHBEf5qbx_VbKWgavxpIuUmJUzCTj1Vk2CbskK64yyLZ7CTvZ-vBjir0WmqNXZFerzYkMkUCEzgDdTif6f-SA5URiKu8njT9djsl6Mu2AYFyxYhWRyOX2
GET {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast/23/example?max=15
Accept: application/json

###

POST {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

Ashesh

###

GET {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast/example?results=5&min=2&max=40
Accept: application/json

###

POST {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast/generate?count=5
Content-Type: application/json

{
  "min":-33,
  "max":33

}
###
GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners
Authorization: Bearer {{token}}
###

GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/1

###


GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/13
Authorization: Bearer {{token}}
###
POST {{FrontLineCleaners.API_HostAddress}}/api/cleaners
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"TopPro Cleaners",
  "Description":"Professional cleaning services",
  "Category":"Complete",
  "HasOwnSupplies":true,
  "ContactEmail":"toppro@info.co.uk",
  "ContactNumber":"7234567344",
  "City":"London",
  "Street":"508 Villa St",
  "PostalCode":"111-330"
}

###
DELETE {{FrontLineCleaners.API_HostAddress}}/api/cleaners/12

###
PATCH {{FrontLineCleaners.API_HostAddress}}/api/cleaners/11
Content-Type: application/json

{
  "Name":"Sys-Co Clean Services",
  "Description":"Excelling in complete cleaning services",
  "HasOwnSupplies":true
}

###
POST {{FrontLineCleaners.API_HostAddress}}/api/cleaners/13/services
Content-Type: application/json

{
  "Name":"Office",
  "Description":"Clean office spaces and buildings",
  "Cost":1175,
  "TimeInHours":10
}
###
GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/13/services
Authorization: Bearer {{token}}
###
GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/1/services/1

###
DELETE {{FrontLineCleaners.API_HostAddress}}/api/cleaners/4/services

###
POST {{FrontLineCleaners.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email":"admin@flc.com",
  "password":"Password1!"
}
###
PATCH {{FrontLineCleaners.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nationality":"Burmese",
  "DateOfBirth":"1996-02-09"
}
###
POST {{FrontLineCleaners.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email":"ae.ashesh@gmail.com",
  "password":"Password1!"
}

###
POST {{FrontLineCleaners.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userEmail":"ae.ashesh@gmail.com",
  "roleName":"User"
}

###
DELETE {{FrontLineCleaners.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userEmail":"ae.ashesh@gmail.com",
  "roleName":"User"
}