@host = http://localhost
@port = 7088
@FrontLineCleaners.API_HostAddress = https://localhost:7088
@token = CfDJ8P0E7vemrNBKtEfmnBM7Qgo_K4r-hXOFkd7J_z_yuxroG5PeTWjHx0Hph0FcSWerkRS9V7w15P01QqT40YE4MQtJmwZwhf9sLa56-vFTTa6HdEsjWyS5_IUO3wAcAWjgTRPTnrP9u7t3yhYsKgElCrE5W6uGxrqTFMjqmj8oCbNE4QgP-Dqp7ViVcyiZ9yyGbzAUTa9jovDSvhZndSC4_vfpsXJrC_F45zPnJce6-fDQzTqi-zhVFM2Q7SJeVsOR4l4ljavZplbsBqN1sznWd3iLLirf8isuTBoQFV2k7eGVIRn2sDxRujpge3kdLEbH5IETTV2XdZkw5eVp1MQenmQvbbp2tOoQcXvBShNTH3iNP3xjQcwh6gW48rpICJDKfiBjitwwMTnLrnFMGEQ1I5IJGJhoxj1MZ4_u0HCrwloLIWdDbVK-PLKyBvTGaFeafzlTuCi8vxkhsHJlP66zidbmYcuipWsa5Tvp5_bdp7Vmf4d28oatUfItbenEWKWjgX2OpdQ8cP54KFd0CT5EkP2iu1NsnvXshTvPoP960HxeNYY-BSb43L4LXHz6xmvC8X_xDqbRbkdRIAz2nqKOsNjXPlheLI1UWoFXc8a1elUQ16ZmC8f76gxIABBgymphAdnpBILhXq5o2ahuRE--xmJpZ9HmxtcCzcrUrPFC4QLBIhhQMtJFYQLgEqmTTvwwzIdNqJwHOmm8bg5aMmowNw8
GET {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast/23/example?max=15
Accept: application/json

###

POST {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

Ashesh

###

GET {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast/example?results=5&min=2&max=40
Accept: application/json

###

POST {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast/generate?count=5
Content-Type: application/json

{
  "min":-33,
  "max":33

}
###
GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners
Authorization: Bearer {{token}}
###

GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/1

###


GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/13

###
POST {{FrontLineCleaners.API_HostAddress}}/api/cleaners
Content-Type: application/json

{
  "Name":"SysCo Clean Services",
  "Description":"Complete cleaning services",
  "Category":"Complete",
  "HasOwnSupplies":true,
  "ContactEmail":"syscocs@info.co.uk",
  "ContactNumber":"7234567340",
  "City":"London",
  "Street":"500 Bluebird St",
  "PostalCode":"110-330"
}

###
DELETE {{FrontLineCleaners.API_HostAddress}}/api/cleaners/12

###
PATCH {{FrontLineCleaners.API_HostAddress}}/api/cleaners/11
Content-Type: application/json

{
  "Name":"Sys-Co Clean Services",
  "Description":"Excelling in complete cleaning services",
  "HasOwnSupplies":true
}

###
POST {{FrontLineCleaners.API_HostAddress}}/api/cleaners/13/services
Content-Type: application/json

{
  "Name":"Office",
  "Description":"Clean office spaces and buildings",
  "Cost":1175,
  "TimeInHours":10
}
###
GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/13/services
###
GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/1/services/1

###
DELETE {{FrontLineCleaners.API_HostAddress}}/api/cleaners/4/services

###
POST {{FrontLineCleaners.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email":"ae.ashesh@gmail.com",
  "password":"Password1!"
}

###
POST {{FrontLineCleaners.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email":"ae.ashesh@gmail.com",
  "password":"Password1!"
}