@host = http://localhost
@port = 7088
@FrontLineCleaners.API_HostAddress = https://localhost:7088
@token = CfDJ8P0E7vemrNBKtEfmnBM7Qgo62wUysmd2kdLbByxOfcV525R9GUCfPyz_WLpGls9644R0E60pThLfemJfniLavhtCXHTBb_Om865sGVpTIJDtQrQPT4zukfm503l0s8OoSGa3SzpAMhF9_bNfIXi39HA86CU-2SwDSjGTsQ0La_I6lvnlJ8ecLxNzvErv2F1A-V0b0zvLbixKqKZ_o0czQhdPwiEXpXn-Krkk2okzySyIrPcfj8hJJP7xU1yOu6fgry9n4wpNWUDmPMk9A-WSfIWtA_WbV3jKMdY_w2D_rgEDarO9sJf5AviUAK2le4fieoBuNxZkdexqb4msj_R1jJrJKdHInZlFtd5f7t-yyC3UodaB5rWdqY7hMs9vgKW7l4GGHj4iQE7xsn2-dmOif_08jrkKq7a0f4GjhDtRsBBaSr2BoHC9gvf3hKeCtrWFxOv2adDpOyWO6b-aO-YbXtIHvfkMj8zQIzJhq9Q9sj98CiPEwRQBjmG2xydJzyf7hEnKQsXa4ysxMwMB6EvuijwOz9o34O4KFRIi67wntxE0ZuDOadS8pogJqjKnzsj-3QT-XcG3CkFEH0Fi0r5aCoLDYK82Q5Sno44whWaSzoNxKJAwXvDjf9nZUOm3UTD0S_gROYFd82FGcqpun8377kGUnW4sbU6DnIuBGOd1vNLkZ1Qe53NqVp4TVZ7O0s5jNFoopXeR-YKxda4h2aSi07nzZvWbNi4x2sycEHtjSNTUjvA-5K3jnXofPo9ArY7ApTOZs9O5BvG6gHu7KIKRGYDYkxU3sEMtPBzIdtRyiwDF
GET {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast/23/example?max=15
Accept: application/json

###

POST {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

Ashesh

###

GET {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast/example?results=5&min=2&max=40
Accept: application/json

###

POST {{FrontLineCleaners.API_HostAddress}}/api/weatherforecast/generate?count=5
Content-Type: application/json

{
  "min":-33,
  "max":33

}
###
GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners
Authorization: Bearer {{token}}
###

GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/1

###


GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/13

###
POST {{FrontLineCleaners.API_HostAddress}}/api/cleaners
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"TopPro Cleaners",
  "Description":"Professional cleaning services",
  "Category":"Complete",
  "HasOwnSupplies":true,
  "ContactEmail":"toppro@info.co.uk",
  "ContactNumber":"7234567344",
  "City":"London",
  "Street":"508 Villa St",
  "PostalCode":"111-330"
}

###
DELETE {{FrontLineCleaners.API_HostAddress}}/api/cleaners/12

###
PATCH {{FrontLineCleaners.API_HostAddress}}/api/cleaners/11
Content-Type: application/json

{
  "Name":"Sys-Co Clean Services",
  "Description":"Excelling in complete cleaning services",
  "HasOwnSupplies":true
}

###
POST {{FrontLineCleaners.API_HostAddress}}/api/cleaners/13/services
Content-Type: application/json

{
  "Name":"Office",
  "Description":"Clean office spaces and buildings",
  "Cost":1175,
  "TimeInHours":10
}
###
GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/13/services
###
GET {{FrontLineCleaners.API_HostAddress}}/api/cleaners/1/services/1

###
DELETE {{FrontLineCleaners.API_HostAddress}}/api/cleaners/4/services

###
POST {{FrontLineCleaners.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email":"admin@flc.com",
  "password":"Password1!"
}

###
POST {{FrontLineCleaners.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email":"admin@flc.com",
  "password":"Password1!"
}

###
POST {{FrontLineCleaners.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userEmail":"ae.ashesh@gmail.com",
  "roleName":"User"
}